# Overriding configuration when started in docker mode
# to start in local mode with maven: -Dspring-boot.run.profiles=docker

spring:
  ## Data repository configuration
  datasource:
    url: jdbc:h2:file:/data/database-customer-service.h2 # persistent when used in docker.
  h2.console:
    enabled: false

info:
  application:
    name: '@project.name@ (docker deployment)'

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/