-- Dataset generated by ChatGPT
-- These data are automatically load at startup when using an in-memory database (e.g., debug)
-- Use http://localhost:9090/h2-console to access the H2 database web UI (sa, password)

INSERT INTO
    customers (FIRST_NAME, LAST_NAME, MEMBER_ID, HRM_DEVICE_ID, TARGET)
VALUES
    ('Homer',   'Simpson', 'Springfield_001', 'Polar001',   4),
    ('Peter',   'Griffin', 'Quahog_002',      'Garmin002',  3),
    ('Tony',    'Stark',   'Malibu_003',      'Suunto003',  2),
    ('Bruce',   'Wayne',   'Gotham_004',      'Wahoo004',   1),
    ('Clark',   'Kent',    'Metropolis_005',  'Fitbit005',  0),
    ('Darth',   'Vader',   'DeathStar_006',   'Coros006',   4),
    ('Walter',  'White',   'Albuquerque_007', 'Apple007',   3),
    ('Sheldon', 'Cooper',  'Pasadena_008',    'Samsung008', 2),
    ('Marty',   'McFly',   'HillValley_009',  'Garmin009',  1),
    ('Ferris',  'Bueller', 'Chicago_010',     'Suunto010',  0),
    ('Don',     'Draper',  'NYC_011',         'Polar011',   4),
    ('Jon',     'Snow',    'Winterfell_012',  'Wahoo012',   3),
    ('Arya',    'Stark',   'Winterfell_013',  'Fitbit013',  2),
    ('Ron',     'Swanson', 'Pawnee_014',      'Coros014',   1),
    ('Leslie',  'Knope',   'Pawnee_015',      'Apple015',   0),
    ('Michael', 'Scott',   'Scranton_016',    'Samsung016', 4),
    ('Liz',     'Lemon',   'NYC_017',         'Garmin017',  3),
    ('Dwight',  'Schrute', 'Scranton_018',    'Suunto018',  2),
    ('Jack',    'Sparrow', 'Caribbean_019',   'Polar019',   1),
    ('Indiana', 'Jones',   'Cairo_020',       'Wahoo020',   0);
